import { z } from "zod";

const unlimitedValue = z.union([z.number().min(0), z.null()]);

export const planLimitsSchema = z.object({
  admins: unlimitedValue,
  instructors: unlimitedValue,
  students: unlimitedValue,
  courses: unlimitedValue,
  sections: unlimitedValue,
  lessons: unlimitedValue,
  videos: unlimitedValue,
  certificates: unlimitedValue,
  quizzes: unlimitedValue,
  assignments: unlimitedValue,
  discussionThreads: unlimitedValue,
  bookmarks: unlimitedValue,
  notes: unlimitedValue,
  notificationsPerMonth: unlimitedValue,
  apiRequests: unlimitedValue,
  storage: unlimitedValue,
  bandwidth: unlimitedValue,
  maximumUploadSize: unlimitedValue,
  maximumVideoDuration: unlimitedValue,
});

export const planFeaturesSchema = z.object({
  courses: z.boolean(),
  certificates: z.boolean(),
  assignments: z.boolean(),
  quizzes: z.boolean(),
  discussions: z.boolean(),
  notes: z.boolean(),
  bookmarks: z.boolean(),
  basicAnalytics: z.boolean(),
  advancedAnalytics: z.boolean(),
  bunnyStream: z.boolean(),
  videoStreaming: z.boolean(),
  videoDownloadProtection: z.boolean(),
  videoAnalytics: z.boolean(),
  customBranding: z.boolean(),
  whiteLabel: z.boolean(),
  customDomain: z.boolean(),
  auditLogs: z.boolean(),
  activityLogs: z.boolean(),
  apiAccess: z.boolean(),
  webhooks: z.boolean(),
  smtp: z.boolean(),
  stripe: z.boolean(),
  paypal: z.boolean(),
  zoom: z.boolean(),
  googleMeet: z.boolean(),
  microsoftTeams: z.boolean(),
  aiAssistant: z.boolean(),
  aiGrading: z.boolean(),
  aiAnalytics: z.boolean(),
});

export const planVideoStorageSchema = z.object({
  storageLimit: z.number().min(0),
  storageUsed: z.number().min(0),
  bandwidthLimit: z.number().min(0),
  bandwidthUsed: z.number().min(0),
  videosLimit: z.number().min(0),
  videosUsed: z.number().min(0),
  maximumUploadSize: z.number().min(0),
  maximumVideoDuration: z.number().min(0),
  allowedFormats: z.array(z.enum(["mp4", "mov", "avi", "mkv", "webm"])),
  allowedQualities: z.array(z.enum(["720", "1080", "2k", "4k"])),
});

export const planBrandingSchema = z.object({
  color: z.string().min(1, "الرجاء اختيار لون"),
  gradient: z.string().min(1, "الرجاء اختيار تدرج"),
  icon: z.string().min(1, "الرجاء اختيار أيقونة"),
  recommendedRibbon: z.boolean(),
  popularRibbon: z.boolean(),
});

export const planIntegrationsSchema = z.object({
  allowBunnyStorage: z.boolean(),
  allowBunnyStream: z.boolean(),
  allowSmtp: z.boolean(),
  allowStripe: z.boolean(),
  allowPaypal: z.boolean(),
  allowZoom: z.boolean(),
  allowMicrosoftTeams: z.boolean(),
  allowGoogleMeet: z.boolean(),
});

export const planFormSchema = z.object({
  name: z.string().min(1, "اسم الباقة مطلوب"),
  slug: z.string().optional().default(""),
  description: z.string().optional().default(""),
  badge: z.enum(["most_popular", "best_value", "enterprise", "custom", "new", "limited"]).nullable().optional(),
  monthlyPrice: z.coerce.number().min(0).optional().default(0),
  yearlyPrice: z.coerce.number().min(0).optional().default(0),
  currency: z.string().optional().default("SAR"),
  displayOrder: z.coerce.number().min(0).optional().default(0),
  trialEnabled: z.boolean().optional().default(false),
  trialDays: z.coerce.number().min(0).optional().default(0),
  recommended: z.boolean().optional().default(false),
  visible: z.boolean().optional().default(true),
  active: z.boolean().optional().default(false),
  status: z.enum(["draft", "active", "hidden", "archived"]).optional().default("draft"),
  color: z.string().optional().default("#6366f1"),
  gradient: z.string().optional().default("from-indigo-500 to-purple-600"),
  icon: z.string().optional().default("rocket"),
  limits: planLimitsSchema.optional().default({
    admins: null, instructors: null, students: null, courses: null,
    sections: null, lessons: null, videos: null, certificates: null,
    quizzes: null, assignments: null, discussionThreads: null,
    bookmarks: null, notes: null, notificationsPerMonth: null,
    apiRequests: null, storage: null, bandwidth: null,
    maximumUploadSize: null, maximumVideoDuration: null,
  }),
  features: planFeaturesSchema.optional().default({
    courses: false, certificates: false, assignments: false, quizzes: false,
    discussions: false, notes: false, bookmarks: false,
    basicAnalytics: false, advancedAnalytics: false,
    bunnyStream: false, videoStreaming: false, videoDownloadProtection: false, videoAnalytics: false,
    customBranding: false, whiteLabel: false, customDomain: false,
    auditLogs: false, activityLogs: false, apiAccess: false, webhooks: false,
    smtp: false, stripe: false, paypal: false, zoom: false, googleMeet: false, microsoftTeams: false,
    aiAssistant: false, aiGrading: false, aiAnalytics: false,
  }),
  videoStorage: planVideoStorageSchema.partial().optional().default({}),
  branding: planBrandingSchema.partial().optional().default({}),
  integrations: planIntegrationsSchema.optional().default({
    allowBunnyStorage: false, allowBunnyStream: false, allowSmtp: false,
    allowStripe: false, allowPaypal: false, allowZoom: false,
    allowMicrosoftTeams: false, allowGoogleMeet: false,
  }),
});

export type PlanFormValues = z.infer<typeof planFormSchema>;
