import { z } from "zod";

export const createCourseSchema = z.object({
  title: z.string().min(1, "عنوان الدورة مطلوب").max(255, "العنوان طويل جداً"),
  subtitle: z.string().max(255, "العنوان الفرعي طويل جداً").optional().or(z.literal("")),
  shortDescription: z.string().max(500, "الوصف المختصر طويل جداً").optional().or(z.literal("")),
  description: z.string().optional().or(z.literal("")),
  fullDescription: z.string().optional().or(z.literal("")),
  visibility: z.enum(["private", "public", "unlisted"], { required_error: "نوع الظهور مطلوب" }),
  difficulty: z.enum(["beginner", "intermediate", "advanced", "all_levels"], { required_error: "المستوى مطلوب" }),
  language: z.string().min(1, "اللغة مطلوبة").max(10, "اللغة طويلة جداً"),
  duration: z.number().min(0, "المدة يجب أن تكون 0 أو أكثر").nullable().optional(),
  pricingType: z.enum(["free", "one_time", "subscription"], { required_error: "نوع السعر مطلوب" }),
  price: z.number().min(0, "السعر يجب أن يكون 0 أو أكثر").nullable().optional(),
  currency: z.string().length(3, "العملة يجب أن تكون 3 أحرف").nullable().optional().or(z.literal("")),
  discountPrice: z.number().min(0, "سعر الخصم يجب أن يكون 0 أو أكثر").nullable().optional(),
  enrollmentLimit: z.number().min(0, "حد التسجيل يجب أن يكون 0 أو أكثر").nullable().optional(),
  startDate: z.string().nullable().optional(),
  endDate: z.string().nullable().optional(),
  certificateEnabled: z.boolean().optional(),
  seoTitle: z.string().max(255).optional().or(z.literal("")),
  seoDescription: z.string().max(500).optional().or(z.literal("")),
  seoKeywords: z.string().max(500).optional().or(z.literal("")),
  categoryIds: z.array(z.number()).optional(),
  tagIds: z.array(z.number()).optional(),
  requirements: z.array(z.string().max(500, "المتطلب طويل جداً")).optional(),
  learningOutcomes: z.array(z.string().max(500, "النتيجة طويلة جداً")).optional(),
  targetAudience: z.array(z.string().max(500, "الجمهور المستهدف طويل جداً")).optional(),
});

export const updateCourseSchema = z.object({
  title: z.string().min(1, "عنوان الدورة مطلوب").max(255, "العنوان طويل جداً").optional(),
  subtitle: z.string().max(255).optional().or(z.literal("")),
  shortDescription: z.string().max(500).optional().or(z.literal("")),
  description: z.string().optional().or(z.literal("")),
  fullDescription: z.string().optional().or(z.literal("")),
  visibility: z.enum(["private", "public", "unlisted"]).optional(),
  difficulty: z.enum(["beginner", "intermediate", "advanced", "all_levels"]).optional(),
  language: z.string().max(10, "اللغة طويلة جداً").optional(),
  duration: z.number().min(0).nullable().optional(),
  pricingType: z.enum(["free", "one_time", "subscription"]).optional(),
  price: z.number().min(0).nullable().optional(),
  currency: z.string().length(3).nullable().optional().or(z.literal("")),
  discountPrice: z.number().min(0).nullable().optional(),
  enrollmentLimit: z.number().min(0).nullable().optional(),
  startDate: z.string().nullable().optional(),
  endDate: z.string().nullable().optional(),
  certificateEnabled: z.boolean().optional(),
  featured: z.boolean().optional(),
  seoTitle: z.string().max(255).optional().or(z.literal("")),
  seoDescription: z.string().max(500).optional().or(z.literal("")),
  seoKeywords: z.string().max(500).optional().or(z.literal("")),
  categoryIds: z.array(z.number()).optional(),
  tagIds: z.array(z.number()).optional(),
  requirements: z.array(z.string().max(500)).optional(),
  learningOutcomes: z.array(z.string().max(500)).optional(),
  targetAudience: z.array(z.string().max(500)).optional(),
});

export type CreateCourseFormValues = z.infer<typeof createCourseSchema>;
export type UpdateCourseFormValues = z.infer<typeof updateCourseSchema>;
