[program:teachify-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/teachify/apps/api/artisan queue:work database --queue=default --sleep=3 --tries=3 --max-time=3600 --max-jobs=1000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/teachify/logs/queue-default.log
stopwaitsecs=3600
stoprestart_delay=5

[program:teachify-scheduler]
process_name=%(program_name)s
command=php /var/www/teachify/apps/api/artisan schedule:work
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/teachify/logs/scheduler.log
stopwaitsecs=10
