// Teachify SaaS - PM2 Ecosystem Configuration
// Usage: pm2 start ecosystem.config.js

module.exports = {
  apps: [
    // Laravel is served by PHP-FPM via Caddy — no PM2 process needed.
    {
      name: "teachify-next",
      script: "node_modules/.bin/next",
      args: "start -p 3000",
      cwd: "./apps/web",
      instances: "max",
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/next-error.log",
      out_file: "./logs/next-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      exp_backoff_restart_delay: 100,
      max_restarts: 10,
      min_uptime: "5s",
    },
    {
      name: "teachify-queue",
      script: "vendor/bin/artisan",
      args: "queue:work --sleep=3 --tries=3 --max-time=3600 --max-jobs=1000",
      cwd: "./apps/api",
      instances: 2,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        APP_ENV: "production",
        APP_DEBUG: "false",
      },
      error_file: "./logs/queue-error.log",
      out_file: "./logs/queue-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      exp_backoff_restart_delay: 100,
      max_restarts: 10,
      min_uptime: "5s",
    },
    {
      name: "teachify-reverb",
      script: "vendor/bin/artisan",
      args: "reverb:start --host=127.0.0.1 --port=8080 --no-interaction",
      cwd: "./apps/api",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        APP_ENV: "production",
        APP_DEBUG: "false",
      },
      error_file: "./logs/reverb-error.log",
      out_file: "./logs/reverb-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      exp_backoff_restart_delay: 100,
      max_restarts: 10,
      min_uptime: "5s",
    },
    {
      name: "teachify-scheduler",
      script: "vendor/bin/artisan",
      args: "schedule:work",
      cwd: "./apps/api",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      env: {
        APP_ENV: "production",
        APP_DEBUG: "false",
      },
      error_file: "./logs/scheduler-error.log",
      out_file: "./logs/scheduler-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_restarts: 10,
    },
  ],
};
